name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.3.0
homepage: https://github.com/Kaven-Fork/dart_otp

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  crypto:
  base32:

dev_dependencies:
  test:
  test_coverage:

dependency_overrides:
  meta: 1.6.0