name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.3.0
homepage: https://github.com/Kaven-Fork/dart_otp

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto:
  base32:
    git:
      url: https://github.com/Kaven-Fork/dart-base32
      ref: master

dev_dependencies:
  test:
  test_coverage: